###########################
## Users resource endpoints

### get all users
GET http://localhost:3000/api/users

### get user by id
GET http://localhost:3000/api/users/3

### create a new user (user registration)
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "BatMan",
  "password": "user4pwd",
  "email": "bat@example.com",
  "birthday": "2019-05-13"
}

### modify an existing user by id
PUT http://localhost:3000/api/users/4
content-type: application/json

{
  "username": "EditedMan",
  "password": "user4pwd",
  "birthday": "1989-05-14",
  "email": "editedmail@example.com"
}

### delete a user (by id)
DELETE http://localhost:3000/api/users/8

### user login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "Batman",
  "password": "user4pwd"
}

### get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6IkJhdE1hbiIsImVtYWlsIjoiYmF0QGV4YW1wbGUuY29tIiwiYmlydGhkYXkiOiIyMDE5LTA1LTEyVDIxOjAwOjAwLjAwMFoiLCJjcmVhdGVfdGltZSI6IjIwMjUtMDMtMjNUMTQ6NTI6NTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQyNzQxODA4LCJleHAiOjE3NDI4MjgyMDh9.MGCtDmUDMGaeJrw3sMfYQliHq7TmP_qVCzAYxRQci_A


### post a new entry
POST http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6IkJhdE1hbiIsImVtYWlsIjoiYmF0QGV4YW1wbGUuY29tIiwiYmlydGhkYXkiOiIyMDE5LTA1LTEyVDIxOjAwOjAwLjAwMFoiLCJjcmVhdGVfdGltZSI6IjIwMjUtMDMtMjNUMTQ6NTI6NTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQyNzQxODA4LCJleHAiOjE3NDI4MjgyMDh9.MGCtDmUDMGaeJrw3sMfYQliHq7TmP_qVCzAYxRQci_A
content-type: application/json

{
 "entry_date": "2025-02-28",
 "bs_value": "7.0",
 "given_dose": "3",
 "giver": "parents",
 "med_name":"pikapika",
 "notes": "50g of carb, eaten 55 perc"
}

### Get user's entries
GET http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6IkJhdE1hbiIsImVtYWlsIjoiYmF0QGV4YW1wbGUuY29tIiwiYmlydGhkYXkiOiIyMDE5LTA1LTEyVDIxOjAwOjAwLjAwMFoiLCJjcmVhdGVfdGltZSI6IjIwMjUtMDMtMjNUMTQ6NTI6NTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQyNzQxODA4LCJleHAiOjE3NDI4MjgyMDh9.MGCtDmUDMGaeJrw3sMfYQliHq7TmP_qVCzAYxRQci_A

### post a new entry
POST http://localhost:3000/api/med
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6IkJhdE1hbiIsImVtYWlsIjoiYmF0QGV4YW1wbGUuY29tIiwiYmlydGhkYXkiOiIyMDE5LTA1LTEyVDIxOjAwOjAwLjAwMFoiLCJjcmVhdGVfdGltZSI6IjIwMjUtMDMtMjNUMTQ6NTI6NTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQyNzQxODA4LCJleHAiOjE3NDI4MjgyMDh9.MGCtDmUDMGaeJrw3sMfYQliHq7TmP_qVCzAYxRQci_A
content-type: application/json

{
 "entry_date": "2025-03-29",
 "med_name":"pikapika",
 "bs_l": "7.0",
 "dosage_l": "2",
 "bs_h": "9.0",
 "dosage_h": "3",
 "notes": "do not give ins below 5, case of below2.5 contact emergency"
}

### Get user's entries
GET http://localhost:3000/api/med
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6IkJhdE1hbiIsImVtYWlsIjoiYmF0QGV4YW1wbGUuY29tIiwiYmlydGhkYXkiOiIyMDE5LTA1LTEyVDIxOjAwOjAwLjAwMFoiLCJjcmVhdGVfdGltZSI6IjIwMjUtMDMtMjNUMTQ6NTI6NTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQyNzQxODA4LCJleHAiOjE3NDI4MjgyMDh9.MGCtDmUDMGaeJrw3sMfYQliHq7TmP_qVCzAYxRQci_A
